# Generated by Django 6.0 on 2025-12-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomingpet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
