# Generated by Django 6.0 on 2025-12-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_rename_message_adoptionrequest_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='full_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='reason',
            field=models.TextField(default='N/A'),
        ),
    ]
